name: Test Action

on:
  push:
    branches: ['dev-master']

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Test Local Action
        id: check
        uses: ./
        with:
          base-image: alpine:3.20
          user-image: kyzimaspb/webone
      - 
        name: Print Output
        run: echo "${{ steps.check.outputs.result }}"
