name: Check if the base Docker image has changed and then rebuild it

on:
  push:
    branches:
      - dev-master

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.check.outputs.result }}
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Test Local Action
        id: check
        uses: ./
        with:
          base-image: alpine:3.20
          user-image: kyzimaspb/webone
  
  build:
    needs: check
    if: ${{ needs.check.outputs.result }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Rebuild Image
        run: echo "Need rebuild image"
